### PR TITLE
ratelimiter: improve logs

### PR DESCRIPTION
**Pull request by yields**
let me know if i can make this even clearer! :)

### CODE REVIEW

**Review by dfuentes — APPROVED** [review]
LGTM

**Comment by yields** [comment]
@dfuentes 

who should take deploying this? :)
i can take it, but you gotta teach me haha

**Comment by dfuentes** [comment]
Deploying is a real pain right now.  You will need to update the docker image version in all the cluster AMI's (https://github.com/segment-infra/images/blob/master/megapool/scripts/rate-limiting-log-proxy.sh for example for megapool).

I just tagged this new one v0.1.5, circle should finish pushing the image to dockerhub within a few minutes.

Once those AMI's are rebuilt, then we need to cycle the ECS clusters to pick em up.  I think if you just do the version bump, then we can wait and let it be deployed along with the next person who does a cluster cycle.

**Comment by yields** [comment]
> I think if you just do the version bump, then we can wait and let it be deployed along with the next person who does a cluster cycle.

sgtm, thanks!

**Pull request merged**
